import Link from "next/link";
import { MarketingNav } from "@/components/v3/marketing/MarketingNav";
import { MarketingFooter } from "@/components/v3/marketing/MarketingFooter";
import { Card } from "@/components/v3/ui";
import { CardGridSection, CheckList, FaqSection, FinalCta, SolutionHero, StepsSection } from "@/components/v3/marketing/MarketingSections";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({ title: "Erebrus for Business - Private Company Network, Firewall and AI", description: "Secure employee and contractor access, protect company systems with managed firewall policies, and run private AI on infrastructure your business controls.", path: "/business" });
export default function BusinessPage() { return <><MarketingNav /><main><SolutionHero eyebrow="Erebrus for Small Businesses and Teams" title="Secure every employee. Control every connection. Keep company AI private." body="Erebrus gives growing businesses a private company network, firewall protection, and private AI workspace without requiring a large internal security team." primary={{label:"Start a Business Pilot",href:"/contact?intent=business-pilot"}} secondary={{label:"Book a Demo",href:"/contact?intent=business-demo"}} note="For remote teams, contractors, internal systems, customer data, and confidential AI workflows." />
  <CardGridSection title="Your company has more entry points than it used to." intro="Employees work from home, contractors need temporary access, internal tools live across clouds and offices, and sensitive information is increasingly copied into AI services. Erebrus brings these access and protection needs into one private workspace." items={[{title:"Remote work",body:"Protect employees connecting through networks the business does not manage."},{title:"Contractor access",body:"Centrally revoke member or device access when work ends."},{title:"Private company systems",body:"Reduce the need to expose internal dashboards and services publicly."},{title:"Confidential AI work",body:"Give sensitive prompts and documents a company-controlled place to be processed."}]} columns={2} />
  <CardGridSection eyebrow="Core capabilities" title="Secure the connection first, then build on it." items={[{title:"Secure employee and contractor access",body:"Give approved users a protected connection to company systems from the office, home, or while travelling."},{title:"Dedicated company VPN gateways",body:"Use infrastructure assigned to the organization through Erebrus, your cloud, or hardware you control."},{title:"Business firewall protection",body:"Apply supported DNS and network policies through Erebrus Shield or Sentinel based on the deployment."},{title:"Private AI for confidential work",body:"Host supported models on company-controlled infrastructure for approved employees."}]} columns={2} />
  <StepsSection title="How the company workspace works." steps={[{title:"Create the workspace",body:"Configure the organization and administrators."},{title:"Add employees and contractors",body:"Assign access supported by current roles and plans."},{title:"Connect through a company gateway",body:"Use a dedicated, cloud-hosted, or self-hosted node."},{title:"Protect company traffic",body:"Apply available Shield or Sentinel policies."},{title:"Keep services private",body:"Make approved internal services reachable through the company network."},{title:"Add private AI",body:"Expose approved model endpoints to authorized members and devices."}]} />
  <CardGridSection eyebrow="Deployment options" title="Choose who controls the infrastructure." items={[{title:"Managed by Erebrus",body:"Use supported dedicated gateways and firewall services included with the selected plan."},{title:"Deployed in your cloud",body:"Run Erebrus inside infrastructure controlled by your organization where supported."},{title:"Deployed on your hardware",body:"Operate the VPN, firewall, and AI host from office, data-centre, or edge hardware managed by your team."}]} />
  <section id="private-ai" className="mx-auto max-w-[1180px] px-4 py-16 md:px-8"><Card className="p-8 md:p-12"><h2 className="text-3xl font-bold md:text-[42px]">Give employees AI without giving up infrastructure control.</h2><p className="mt-4 max-w-3xl text-[var(--text-2)]">Erebrus AI can host supported local models on a workstation or server and make them available through the private network. Model quality, licensing, hardware needs, context limits, and data handling depend on the selected model and deployment.</p><div className="mt-8"><CheckList items={["Confidential document summarization","Internal policy and knowledge assistance","Proposal and report drafting","Private coding assistance","Research synthesis"]} /></div></Card></section>
  <section className="mx-auto max-w-[1180px] px-4 py-16 md:px-8"><Card className="p-8 md:p-12" style={{borderColor:"rgba(255,107,53,.3)"}}><h2 className="text-3xl font-bold">Start with a focused business pilot.</h2><p className="mt-4 max-w-3xl text-[var(--text-2)]">Deploy Erebrus for a small group, protect one company resource, test access revocation, apply baseline firewall policies, and optionally connect one private AI endpoint.</p><div className="mt-7"><CheckList items={["Up to 10 pilot users","One dedicated or customer-controlled VPN gateway","Employee and contractor onboarding","Baseline firewall or DNS policies","One protected company resource","Access-revocation test","Optional private AI endpoint","Deployment review"]} /></div><div className="mt-8 flex flex-wrap gap-5"><Link href="/contact?intent=business-pilot" className="font-semibold text-[var(--accent-hi)]">Start a Business Pilot →</Link><Link href="/contact?intent=deployment" className="font-semibold text-[var(--text-2)]">Discuss Your Deployment →</Link></div></Card></section>
  <FaqSection items={[{question:"Is Erebrus only a VPN?",answer:"No. The business offering combines private network access, firewall protection, and optional private AI hosting. The VPN is the first layer connecting approved users to trusted services."},{question:"Do we need an internal security team?",answer:"Erebrus is intended to reduce deployment and management complexity, but customers remain responsible for devices, accounts, applications, policies, and legal obligations."},{question:"Can Erebrus run in our cloud or office?",answer:"Yes, where supported by the current node deployment and plan. Deployment details should be confirmed during a pilot discussion."},{question:"Does private AI make us compliant?",answer:"No technology automatically creates compliance. Private hosting can provide greater control over infrastructure and data flow while the business remains responsible for lawful processing, access, retention, and oversight."},{question:"Can contractors be removed immediately?",answer:"Administrators can use the member and device revocation behavior currently supported. Automatic time-based expiry is not implied."}]} />
  <FinalCta title="Secure the team first. Add private AI when you are ready." body="Start with employee access and firewall protection, then expand the same private workspace to company-hosted AI." primary={{label:"Start a Business Pilot",href:"/contact?intent=business-pilot"}} secondary={{label:"View Business Pricing",href:"/pricing?audience=business"}} /></main><MarketingFooter /></>; }
