import { MarketingNav } from "@/components/v3/marketing/MarketingNav";
import { MarketingFooter } from "@/components/v3/marketing/MarketingFooter";
import { CardGridSection, FaqSection, FinalCta, SolutionHero, StepsSection } from "@/components/v3/marketing/MarketingSections";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({ title: "Erebrus for Digital Nomads - Secure Work from Anywhere", description: "Protect your connection on hotel, airport, cafe, and coworking Wi-Fi with Erebrus VPN, stealth connectivity, firewall protection, and private local AI.", path: "/digital-nomads" });
const outcomes = [
  { title: "Secure unfamiliar networks", body: "Encrypt your connection before using shared networks in hotels, airports, cafes, and coworking spaces." },
  { title: "Stay connected when ordinary VPN traffic is restricted", body: "Use supported alternative connection modes when the default VPN route is unavailable or blocked." },
  { title: "Reach trusted resources", body: "Connect to approved home, company, or self-hosted services without exposing them directly to the public internet." },
  { title: "Keep sensitive work local", body: "Run supported AI models on your laptop or reach a private model hosted on trusted hardware." },
];
export default function DigitalNomadsPage() { return <><MarketingNav /><main><SolutionHero eyebrow="Erebrus for Digital Nomads" title="Your private connection, wherever work takes you." body="Protect your traffic on airport, hotel, cafe, and coworking Wi-Fi with a privacy-first VPN designed for people who work across borders." primary={{label:"Download Erebrus VPN",href:"/vpn#download"}} secondary={{label:"View VPN Features",href:"/vpn#features"}} note="Fast WireGuard connections, alternative stealth transports, and access from supported devices." />
  <CardGridSection title="Public Wi-Fi should not become a business risk." items={outcomes} columns={2} />
  <StepsSection title="Connect before the network becomes part of your workday." steps={[{title:"Install Erebrus",body:"Set up Erebrus on a supported device."},{title:"Sign in",body:"Use an identity option available on your platform."},{title:"Select a trusted route",body:"Choose an Erebrus gateway or organization network."},{title:"Connect on shared Wi-Fi",body:"Start the protected connection before working."},{title:"Reach approved services",body:"Use private resources and AI endpoints where configured."}]} />
  <CardGridSection eyebrow="VPN first, protection when you need it" title="A practical privacy toolkit for travel." items={[{title:"VPN for everyday work",body:"Secure browsing and work connections while travelling.",href:"/vpn",cta:"Explore VPN"},{title:"Firewall protection",body:"Use supported DNS and network policies to block malicious destinations and unwanted categories.",href:"/firewall",cta:"Explore Firewall"},{title:"Private AI on the road",body:"Keep selected AI workflows on your hardware or a private endpoint.",href:"/ai",cta:"Explore Private AI"}]} />
  <FaqSection items={[{question:"Does Erebrus work on every public Wi-Fi network?",answer:"Network restrictions vary. Erebrus supports multiple connection options, but no VPN can guarantee access on every network or in every jurisdiction."},{question:"Can I access my company network?",answer:"Yes, when your company has configured an Erebrus organization network and granted your account and device access."},{question:"Does private AI require internet access?",answer:"A model running entirely on your device may work offline after it has been downloaded. Models hosted on another trusted device require network access to that device."},{question:"Is Erebrus only for crypto users?",answer:"No. Use the sign-in options available on your platform. Wallet-based identity remains available, but it is not required to understand the product."}]} />
  <FinalCta title="Work from anywhere without treating every network as trusted." body="Start with Erebrus VPN and add the protection your work requires." primary={{label:"Download Erebrus VPN",href:"/vpn#download"}} secondary={{label:"Compare Personal Plans",href:"/pricing?audience=personal"}} /></main><MarketingFooter /></>; }
