import { MarketingNav } from "@/components/v3/marketing/MarketingNav";
import { MarketingFooter } from "@/components/v3/marketing/MarketingFooter";
import { CardGridSection, FinalCta, ProductFlow, SolutionHero, StepsSection } from "@/components/v3/marketing/MarketingSections";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({ title: "Erebrus Firewall - DNS and Network Protection for Devices and Teams", description: "Block malicious destinations, apply safer DNS policies, and protect personal or company connections with Erebrus Shield and Erebrus Sentinel.", path: "/firewall" });
export default function FirewallPage() { return <><MarketingNav /><main><SolutionHero eyebrow="Erebrus Firewall" title="Stop harmful traffic before it reaches the device." body="Add DNS and network protection to Erebrus connections, block malicious or unwanted destinations, and apply policies across supported personal, family, and business deployments." primary={{label:"Compare Plans",href:"/pricing"}} secondary={{label:"Explore for Business",href:"/business"}} compactVisual />
  <CardGridSection eyebrow="Two levels of protection" title="Choose protection for the way you connect." items={[{eyebrow:"Community protection",title:"Erebrus Shield",body:"DNS-based protection for personal, family, and team deployments. Use supported allow lists, block lists, and category policies to reduce exposure to malicious or unwanted domains."},{eyebrow:"Business firewall",title:"Erebrus Sentinel",body:"Network and DNS policy enforcement for supported business deployments that need stronger control, visibility, and managed protection on Erebrus nodes."}]} columns={2} />
  <section className="mx-auto max-w-[1180px] px-4 py-16 md:px-8"><h2 className="mb-10 text-3xl font-bold md:text-[44px]">Protection built into the connection path.</h2><ProductFlow /></section>
  <StepsSection title="How firewall protection is applied." steps={[{title:"Connect through Erebrus VPN",body:"The device establishes its encrypted connection."},{title:"Route through the assigned gateway",body:"Requests pass through the configured firewall service."},{title:"Apply supported policies",body:"Shield or Sentinel evaluates DNS or network policy."},{title:"Continue approved traffic",body:"Allowed requests reach the internet or private service."},{title:"Review available events",body:"Authorized administrators see the logs exposed by their deployment."}]} />
  <CardGridSection eyebrow="Common use cases" title="Practical protection at home, away, and at work." items={[{title:"Malware and phishing",body:"Block supported malicious-domain lists."},{title:"Trackers and unwanted domains",body:"Reduce connections to selected unwanted destinations."},{title:"Family categories",body:"Apply family-selected policies on supported deployments."},{title:"Company rules",body:"Use allow and deny lists for supported business connections."}]} columns={4} />
  <FinalCta title="Add protection to every Erebrus connection." body="Start with Shield for supported DNS protection or discuss Sentinel for a business deployment." primary={{label:"Compare Plans",href:"/pricing"}} secondary={{label:"Start a Business Pilot",href:"/contact?intent=business-pilot"}} /></main><MarketingFooter /></>; }
