import { MarketingNav } from "@/components/v3/marketing/MarketingNav";
import { MarketingFooter } from "@/components/v3/marketing/MarketingFooter";
import { CardGridSection, FaqSection, FinalCta, SolutionHero, StepsSection } from "@/components/v3/marketing/MarketingSections";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata({ title: "Erebrus for Families - Safer Private Internet Across Devices", description: "Protect family devices at home and away with private VPN access, DNS and firewall policies, and optional private AI on trusted household hardware.", path: "/families" });
export default function FamiliesPage() { return <><MarketingNav /><main><SolutionHero eyebrow="Erebrus for Families" title="A safer private connection for every family device." body="Protect phones, tablets, and computers at home and away, block harmful destinations, and manage family protection without relying only on the home router." primary={{label:"Protect My Family",href:"#app"}} secondary={{label:"Compare Family Options",href:"/pricing?audience=personal"}} />
  <CardGridSection title="Protection that follows the people you care about." items={[{title:"Protection beyond the home router",body:"Keep supported devices protected on home Wi-Fi, mobile networks, and public connections."},{title:"Block harmful destinations",body:"Apply supported DNS and firewall categories selected by the family administrator."},{title:"Manage devices in one place",body:"Add approved family devices without sharing raw VPN configuration details between everyone."},{title:"Respect individual privacy",body:"Manage protection policies and device access without positioning Erebrus as a tool for reading every member's private browsing activity."}]} columns={2} />
  <StepsSection title="Set up a family network in a few clear steps." steps={[{title:"Create the family organization",body:"Create or select the shared organization."},{title:"Add members and devices",body:"Approve the supported devices that should connect."},{title:"Connect the devices",body:"Route supported devices through the family network."},{title:"Apply Shield policies",body:"Choose available DNS protection policies."},{title:"Revoke devices",body:"Remove a lost, replaced, or unrecognized device where supported."}]} />
  <CardGridSection eyebrow="Erebrus Shield" title="Protection that follows the device." intro="Erebrus Shield can apply supported DNS blocking policies through the family network, helping reduce exposure to malicious and unwanted destinations at home and away. Available policies and visibility depend on the selected plan and deployment; Erebrus is not a replacement for active parenting or device-level controls." items={[{title:"Malware and phishing",body:"Block supported malicious-domain lists before a device opens the destination."},{title:"Family-selected categories",body:"Apply the categories appropriate for the household without exposing individual browsing history."}]} columns={2} />
  <CardGridSection eyebrow="Private AI at home" title="A shared AI assistant that can stay at home." intro="Run supported AI models on a household computer and make them available to approved devices, reducing the need to send selected family notes or documents to a public AI endpoint." items={[{title:"Everyday assistance",body:"Use household-approved models for study assistance, summaries, travel planning, recipes, and organization."},{title:"Trusted access",body:"Let approved phones and computers reach the AI host through the family network."}]} columns={2} />
  <FaqSection items={[{question:"Can the family administrator see everything members browse?",answer:"Erebrus focuses on access and protection policies, not invasive monitoring. The operational metadata available depends on the firewall deployment and documented product behavior."},{question:"Does protection continue outside the house?",answer:"It can when the supported device remains connected to the family Erebrus network."},{question:"Can I remove a lost device?",answer:"Yes, where the existing organization and device-management features support revocation."},{question:"Can family members use private AI from their phones?",answer:"Yes, when an Erebrus AI host is running on an approved device and is reachable through the trusted network."}]} />
  <FinalCta title="Give your family a safer way to connect." body="Protect supported devices at home and away with a private family network." primary={{label:"Get Erebrus",href:"#app"}} secondary={{label:"Compare Personal Plans",href:"/pricing?audience=personal"}} /></main><MarketingFooter /></>; }
